### ISSUE TITLE
No such file or directory: 'combined_data/absa/ae/rest/train.txt'

### ISSUE THREAD

**Issue by HarithaMK14** [rit-git/Snippext_public#10]
Hi, 
Facing below error,
"No such file or directory: 'combined_data/absa/ae/rest/train.txt'.  "
Kindly provide missing datasets

**Comment by yochail** [comment]
no idea why they have been removed, but you can git them from the git history:
https://github.com/rit-git/Snippext_public/tree/60620d013541d7a662233543809aee1e79eebc37

**Comment by HarithaMK14** [comment]
@yochail : yeah, thanks
